services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE:-ubuntu:22.04}
    image: ${PROJECT_NAME:-template}:${TAG:-latest}
    container_name: ${PROJECT_NAME:-ros2-camera-latency-benchmark}_dev
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/runtime-developer
    volumes:
      - ./src:/workspace/src
      - ./test:/workspace/test
      - ./ros2_ws:/workspace/ros2_ws
      - ./scripts:/workspace/scripts
      - ./pixi.lock:/workspace/pixi.lock
      - ./pixi.toml:/workspace/pixi.toml
      - ./pyproject.toml:/workspace/pyproject.toml
      - ./Dockerfile:/workspace/Dockerfilezz
      - ./docker-compose.yaml:/workspace/docker-compose-yaml
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # X11 display forwarding.
      - /dev/bus/usb:/dev/bus/usb:rw # usb devices
    network_mode: host
    privileged: true
    shm_size: 4G
    working_dir: /workspace
    stdin_open: true
    tty: true
    user: "root"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-0}
              capabilities: [gpu]
